-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 16:07:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cafeteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cafeteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cafeteria` DEFAULT CHARACTER SET utf8 ;
USE `db_cafeteria` ;

-- -----------------------------------------------------
-- Table `db_cafeteria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `restablecer` CHAR(1) NULL DEFAULT '1',
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
