-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 08:55:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cafeteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cafeteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cafeteria` DEFAULT CHARACTER SET utf8 ;
USE `db_cafeteria` ;

-- -----------------------------------------------------
-- Table `db_cafeteria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `restablecer` CHAR(1) NULL DEFAULT '1',
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`tipo` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `path` TEXT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`producto` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `path` TEXT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_inti` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_tipo_idx` (`id_tipo` ASC) ,
  CONSTRAINT `fk_producto_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `db_cafeteria`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
